### PR TITLE
Allow multiple ingresses deployed to one namespace

### PR DESCRIPTION
**Pull request by Hi-Fi**
Certificate secret to contain application name to prevent collisions when multiple apps deployed to same namespace

### CODE REVIEW

**Comment by frwickst** [comment]
Has this been a problem for you or is this a precaution?
I'm asking since the secret should be created from the following things:
- The project name (which can be set for each application in a mono-repo for instance)
- The track (this is review/staging/stable)

But then again, I might be overlooking how the pipeline runs on GitHub here, and that there could be things that are not as they should there.
Anyways, I don't think that this is the way to fix this since the secret should already be unique due to how it is created.

**Comment by frwickst** [comment]
I'll leave this open still so that we can have a discussion and maybe change the way this is to be implemented.

**Comment by Hi-Fi** [comment]
> Has this been a problem for you or is this a precaution?
> I'm asking since the secret should be created from the following things:
> 
>     * The project name (which can be set for each application in a mono-repo for instance)
> 
>     * The track (this is review/staging/stable)
> 
> 
> But then again, I might be overlooking how the pipeline runs on GitHub here, and that there could be things that are not as they should there.
> Anyways, I don't think that this is the way to fix this since the secret should already be unique due to how it is created.

Normal secrets yes get the name in the form you described. Issue is, that secret defined in ingress is static (defined https://github.com/andersinno/kolga/blob/5d3a3c86ff5182ab81c37bcbbcd650f913e67bd6/helm/values.yaml#L12), so cert-manager creates same secret for each namespace, and replaces the existing one.

Example is here: https://github.com/City-of-Helsinki/hel-data-pipe/actions/runs/488923565. Ingress is deployed 2 jobs:
- https://github.com/City-of-Helsinki/hel-data-pipe/runs/1711288334?check_suite_focus=true#step:13:49
- https://github.com/City-of-Helsinki/hel-data-pipe/runs/1711288250?check_suite_focus=true#step:13:59
But only one got right certificate, and other uses same certificate than working one (because there's only that one secret)

Hopefully this clarifies the situation.

**Comment by frwickst** [comment]
Alright, I see where I went wrong here, you were talking about the ingress indeed here.
Then I'm wondering if we want to keep the hardcoded value at all now. Maybe this should be moved completely to the code instead of the Helm values.
The max length of a secret is 253 chars, so this should not break anything at least since the `appname` is never that long.

I don't see this as a final fix, but good enough to fix the problem that you are experiencing. One thing that is bothering me a bit is the fact that this breaks backward compatibility. So if we break it now this way, and then again with a "proper" fix in code, this would mean that we break backward compatibility twice. Or if we made it in code, one could at least make it optional to change, and the old value _could_ still be used at least.

So, could I suggest that we move this to the Python code instead. This could be implemented in project.py and the new default value could break backward compatibility, but it should be definable by the user. So something in lines of:
1. Add a setting's value `K8S_INGRESS_SECRET_NAME` with an empty default value
2. In project.py add the value to `PROJECT_ARG_SETTINGS_MAPPING` with a `K8S_INGRESS_SECRET_NAME` -> `ingress_secret_name` mapping
3. Add an if-statement checking if the value is empty, if empty create a value based on the app name (`self.deploy_name`) and with a postfix something in the lines of `ingress_secret`
4. Pass this value to the Helm chart in kubernetes.py in the `values` variable
5. Remove the hard-coded value from the values.yaml

**Comment by ruriky** [comment]
This probably updates the existing ingress without errors as the ingress' name won't change. :thinking: 
LGTM.

**Pull request merged**
